version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_NAME: spotifymatcherdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: database
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8080"
    depends_on:
      - db
    container_name: backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: frontend